### ISSUE TITLE
Abort request exceeding maxPostSize with HTTP 413

### ISSUE THREAD

**Issue by hankipanky** [javaee/grizzly#1929]
When an incoming request exceeds the configured [maxPostSize](https://grizzly.java.net/docs/2.3/apidocs/org/glassfish/grizzly/http/server/ServerFilterConfiguration.html#setMaxPostSize-long-), grizzly aborts the request with HTTP 400.

Would you be able to please report this as [HTTP 413 Payload Too Large](https://tools.ietf.org/html/rfc7231#section-6.5.11)?

**Comment by rlubke** [comment]
@jashap Hey James, mind looking into this?

**Comment by jashap** [comment]
Sure, I'll take a look

**Comment by hankipanky** [comment]
Hi @rlubke, @jashap,

thanks for this. May I suggest to use `HttpStatus.REQUEST_ENTITY_TOO_LARGE_413.getReasonPhrase()` along with the status code 413?

Thanks, Henning

**Comment by rlubke** [comment]
Ugh, sorry about that.  Fixed.
