### ISSUE TITLE
problem with PooledMemoryManager

### ISSUE THREAD

**Issue by kentsang77** [javaee/grizzly#1938]
I have used HeapMemoryManager for a long time and everything works fine. 
Last week we tried grizzly version 2.3.30 and found that message decoder doesn't work at all.
Last working grizzly version was 2.3.24.
After investigation, we found the default MemoryManager changed to PooledMemoryManager at 2.3.26 and there is a strange issue when allocating a large encoding buffer (say 4M):

```
final MemoryManager memoryManager = obtainMemoryManager(storage);
final Buffer output = memoryManager.allocate(1024 * 1024 * 4); // ok if 4k but not 4m
```
The symptom is :  only null bytes can be read at decoder.
I created a all in 1 class junit for your investigation.
 
[StringMessageFilterTest.zip](https://github.com/javaee/grizzly/files/1022501/StringMessageFilterTest.zip)

**Comment by rlubke** [comment]
@kentsang77 You're aware how to change the default memory manager back to HeapMemoryManager?

**Comment by kofemann** [comment]
Try start jvm with
```
-Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager
```
option

**Comment by kentsang77** [comment]
It is currently doing at production.
All of my service messages are using jdk's ByteBuffer for serialization and deserialization.
I cannot change that to grizzly Buffer.

**Comment by rlubke** [comment]
Then the option you have is a) Set the default memory manager to HeapMemoryManager or b) if the Buffer is composite, copy the ByteBuffer content back to the Buffer.

The latter option isn't ideal for performance reasons.

**Comment by kentsang77** [comment]
My solution is to use a PooledMemoryManagerFactory to init a PooledMemoryManager with large enough DEFAULT_BASE_BUFFER_SIZE (where allocationSize < DEFAULT_BASE_BUFFER_SIZE ).

Personally I think if the PooledMemoryManager cannot handle large buffer size, it should throw exception. At least not just returning a wired empty buffer.
