### ISSUE TITLE
"java.io.IOException: Remotely closed" in HTTPS (AHC)

### ISSUE THREAD

**Issue by carryel** [javaee/grizzly#1939]
I use Grizzly 2.3.30 + AHC 1.9.40.

When the HTTPS Server didn't support Keep-Alive(connection=close), the grizzly http client(AHC) failed to parse the last packet of response.

```
java.util.concurrent.ExecutionException: java.io.IOException: Remotely closed
	at org.glassfish.grizzly.impl.SafeFutureImpl$Sync.innerGet(SafeFutureImpl.java:349)
	at org.glassfish.grizzly.impl.SafeFutureImpl.get(SafeFutureImpl.java:255)
	at com.ning.http.client.providers.grizzly.GrizzlyResponseFuture.get(GrizzlyResponseFuture.java:127)
```

When I debug the SSLBaseFilter#unwrapAll, I could see some strange status of buffers.

https://github.com/javaee/grizzly/blob/2.3.x/modules/grizzly/src/main/java/org/glassfish/grizzly/ssl/SSLBaseFilter.java#L432 and https://github.com/javaee/grizzly/blob/2.3.x/modules/grizzly/src/main/java/org/glassfish/grizzly/ssl/SSLBaseFilter.java#L436
- output: PooledMemoryManager$PoolHeapBuffer "HeapBuffer (541537078) [pos=0 lim=65536 cap=65536]"

https://github.com/javaee/grizzly/blob/2.3.x/modules/grizzly/src/main/java/org/glassfish/grizzly/ssl/SSLBaseFilter.java#L423
- result.output: BuffersBuffer BuffersBuffer (904437980) [pos=6918 lim=72454 cap=72454 bufferSize=2 buffers=[HeapBuffer (541537078) [pos=0 lim=65536 cap=65536], HeapBuffer (1424649899) [pos=0 lim=6918 cap=16384], null, null]]

https://github.com/javaee/grizzly/blob/2.3.x/modules/grizzly/src/main/java/org/glassfish/grizzly/ssl/SSLBaseFilter.java#L465
- output.trim: HeapBuffer (541537078) [pos=0 lim=0 cap=65536]

I think SSLEngine already read the last packet(result.output) but local output didn't be assigned in SSL termination because of https://github.com/javaee/grizzly/blob/2.3.x/modules/grizzly/src/main/java/org/glassfish/grizzly/ssl/SSLBaseFilter.java#L436.

Unfortunately, I couldn't reproduce it with simple testcase but sometimes I met it in production environment.

**Comment by carryel** [comment]
When I tried to fix it simply like this(https://github.com/carryel/grizzly/blob/2.3.x/modules/grizzly/src/main/java/org/glassfish/grizzly/ssl/SSLBaseFilter.java#L423L445), I didn't met the error.

**Comment by rlubke** [comment]
@carryel Could you create a pull request?

**Comment by carryel** [comment]
@rlubke Sure. I just create a PR. https://github.com/javaee/grizzly/pull/1940

**Comment by rlubke** [comment]
@carryel I've merged the PR.  I'll take care of porting to 2.4.x and master.

**Comment by carryel** [comment]
@rlubke Thanks! Perhaps could I know when the next release of 2.3.x will be able?

**Comment by rlubke** [comment]
@carryel Most likely by the end of the week.

**Comment by rlubke** [comment]
@carryel I'm not sure if you've subscribed to the new discussion group, but 2.3.31 has been released.

**Comment by carryel** [comment]
@rlubke Thanks a lot. I already subscribed. :-)
