### ISSUE TITLE
Embed Grizzly (glassfish) Servlet Container with Spring Boot Java

### ISSUE THREAD

**Issue by rahulrsingh09** [javaee/grizzly#1948]
Spring boot by default uses Tomcat as an Internal Embedded Servlet Container . It has also got support for Jetty and UnderTow.

I have build a Restful Application using spring boot . But now i need to deploy it on Grizzly (Glassfish) Servlet Container .

How do i embed my application to run on grizzly as spring dosen't have support for the same.

https://github.com/spring-projects/spring-boot/issues/5015.

Please help as i researched a lot on thistopic but i coudnt get any link that shows how to embed a new Servlet Container for our spring boot app that spring dosent have support for.

Question Raised on stack
https://stackoverflow.com/questions/44565549/embed-grizzly-glassfish-servlet-container-with-spring-boot-java

**Comment by rlubke** [comment]
Are you trying to deploy on Glassfish or Grizzly standalone.  Don't conflate the two.  Glassfish has it's own Servlet container and uses Grizzly for networking and low-level HTTP.

**Comment by rahulrsingh09** [comment]
@rlubke i want to deploy it to glassfish. what is the difference between the two can you please elloborate it will be great if you helped

**Comment by rlubke** [comment]
You'll want to use GlassFish embedded.  

Please see the documentation:  [https://javaee.github.io/glassfish/doc/4.0/embedded-server-guide.pdf](https://javaee.github.io/glassfish/doc/4.0/embedded-server-guide.pdf).

I'm not familiar with the embedded API.  You best best is to review the documentation and ask specific questions here:  [https://javaee.groups.io/g/glassfish](https://javaee.groups.io/g/glassfish).
