### ISSUE TITLE
SameThreadIOStrategy selectors monitoring

### ISSUE THREAD

**Issue by szymonrusiecki** [javaee/grizzly#1953]
Is there a way to monitor number of active selectors?
Is there a indicator that selectors are running close to the limit?

Strategy: SameThreadIOStrategy 
Grizzly version: org.glassfish.grizzly:grizzly-framework:2.3.28

**Comment by rlubke** [comment]
Review the documentation on monitoring [1]. Selector runners can be monitored via this facility in association with the kernel thread pool.

[1] https://javaee.github.io/grizzly/monitoring.html
