### ISSUE TITLE
Regression due to close listener order not respected

### ISSUE THREAD

**Issue by afelisatti** [javaee/grizzly#1968]
Changes for #1962 did not take into account the order in which the close listeners were registered. As a result the close reason could be missing when several filters where present (such as SSL). I'll be sending a PR to fix this.

**Comment by afelisatti** [comment]
Thanks, @rlubke. Any thoughts on when a 2.3.x release could be available to avoid this issue?

**Comment by rlubke** [comment]
I'll work on a release this week.

**Comment by afelisatti** [comment]
Thank you!

**Comment by rlubke** [comment]
Release complete.

**Comment by afelisatti** [comment]
PR sent to GAHC (https://github.com/javaee/grizzly-ahc/pull/16)
