### ISSUE TITLE
java.lang.NumberFormatException from SoapUI test case

### ISSUE THREAD

**Issue by Steven-J-Curtis** [javaee/grizzly#1999]
Using grizzly version 2.3.35 embedded within Mule server version 3.8.6

Raw HTTP request:

GET https://infobloxlab.w.local.services.ehi.com/wapi/v2.3.1/record:host?name~=v1000015* HTTP/1.1
Accept-Encoding: gzip,deflate
Authorization: Basic **********************
Host: infobloxlab.w.local.services.ehi.com
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)

Expected raw HTTP response:

HTTP/1.1 200 
Date: Sat, 31 Mar 2018 00:12:57 GMT
Server: Apache
Cache-Control: no-cache, no-store
name~: v1000015*
Pragma: no-cache
Content-Type: application/json
Set-Cookie: [Lorg.apache.commons.httpclient.Cookie;@1c6e620a
Keep-Alive: timeout=15, max=500
Connection: Keep-Alive
Transfer-Encoding: chunked

[
    {
        "_ref": "record:host/ZG5zLmhvc3QkLl9kZWZhdWx0LmNvbS5laGkuYnJhbmNoLnBvcy52MTAwMDAxNS0yODQwOTI0Nzk:v1000015-284092479.pos.branch.ehi.com/Internal", 
        "ipv4addrs": [
            {
                "_ref": "record:host_ipv4addr/ZG5zLmhvc3RfYWRkcmVzcyQuX2RlZmF1bHQuY29tLmVoaS5icmFuY2gucG9zLnYxMDAwMDE1LTI4NDA5MjQ3OS4xMC4yMjQuMS4xMDAu:10.224.1.100/v1000015-284092479.pos.branch.ehi.com/Internal", 
                "configure_for_dhcp": true, 
                "host": "v1000015-284092479.pos.branch.ehi.com", 
                "ipv4addr": "10.224.1.100", 
                "mac": "60:c7:98:2e:31:0f"
            }
        ], 
        "name": "v1000015-284092479.pos.branch.ehi.com", 
        "view": "Internal"
    }, 
    {
        "_ref": "record:host/ZG5zLmhvc3QkLl9kZWZhdWx0LmNvbS5laGkuYnJhbmNoLnBvcy52MTAwMDAxNS0zMjEzMjEzMjE:v1000015-321321321.pos.branch.ehi.com/Internal", 
        "ipv4addrs": [
            {
                "_ref": "record:host_ipv4addr/ZG5zLmhvc3RfYWRkcmVzcyQuX2RlZmF1bHQuY29tLmVoaS5icmFuY2gucG9zLnYxMDAwMDE1LTMyMTMyMTMyMS4xMC4yMjQuMS4xMDEu:10.224.1.101/v1000015-321321321.pos.branch.ehi.com/Internal", 
                "configure_for_dhcp": true, 
                "host": "v1000015-321321321.pos.branch.ehi.com", 
                "ipv4addr": "10.224.1.101", 
                "mac": "19:96:19:92:19:59"
            }
        ], 
        "name": "v1000015-321321321.pos.branch.ehi.com", 
        "view": "Internal"
    }
]

Instead, attached exception is thrown.
[grizzly-stack-trace.txt](https://github.com/javaee/grizzly/files/1865029/grizzly-stack-trace.txt)

**Comment by anajosep** [comment]
@Steven-J-Curtis : Can you please raise this issue under https://github.com/eclipse-ee4j/grizzly/issues
The project has been moved to the Eclipse Foundation.

**Comment by anajosep** [comment]
@Steven-J-Curtis :  I am closing this bug and archiving this repository. Please file the bug Grizzly project hosted under Eclipse EE4J Organization (https://github.com/eclipse-ee4j/grizzly/issues).
